package Menu;

import datamaster.Awal;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

/**
 *
 * @author Asus
 */
public class Login extends javax.swing.JFrame {

    private Connection connection = Koneksi.getKoneksi();
    private Statement stm;
    private ResultSet sql;
    public static String role = "Admin";
    private Awal aw;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);// center form in the screen
    }

    public String Menu(String tes) {
        return tes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(324, 0));
        jPanel2.setLayout(null);

        username.setBackground(new java.awt.Color(204, 204, 204));
        username.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usernameMouseExited(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username);
        username.setBounds(350, 70, 199, 35);

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.setForeground(new java.awt.Color(102, 102, 102));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password);
        password.setBounds(350, 130, 199, 35);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_male_user_35px.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(290, 70, 35, 35);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_key_35px.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(290, 130, 35, 35);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Untitled-1.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 60, 190, 170);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_login_rounded_up_30px_2.png"))); // NOI18N
        jLabel7.setText("LOGIN");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(410, 190, 100, 32);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Buat Akun disini");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);
        jLabel9.setBounds(390, 240, 120, 17);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel8.setText("LOGIN");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(420, 30, 68, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
            //username.setText("");
    }//GEN-LAST:event_usernameMouseClicked

    private void usernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseExited
        // TODO add your handling code here:
        //username.setText("username");
    }//GEN-LAST:event_usernameMouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if (username.getText().equals("") && password.getText().equals("")) {
            System.out.println("salah");

        } else {
            try {
                connection = Koneksi.getKoneksi();
                stm = connection.createStatement();
                System.out.println("select * from regis where Username='" + username.getText() + "'and Password='" + password.getText() + "'");
                sql = stm.executeQuery("select * from regis where Username='" + username.getText() + "'and Password='" + password.getText() + "'");
                if (sql.next()) {
                    if (password.getText().equals(sql.getString("Password"))) {
                        JOptionPane.showMessageDialog(null, "Berhasil Login", "CV Adhi Rahayu", JOptionPane.INFORMATION_MESSAGE);
                        try {
                            String sql = "select * from regis where Username='" + username.getText() + "'";
                            PreparedStatement pst = connection.prepareStatement(sql);
                            ResultSet resultSet = pst.executeQuery(sql);
                            while (resultSet.next()) {
                                role = resultSet.getString("role");
                                System.out.println(role);
                            }
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                        this.dispose();
                        this.setVisible(false);
                        Awal aw = new Awal();
                        aw.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "username dan password salah", "CV Adhi Rahayu", JOptionPane.INFORMATION_MESSAGE);
                        username.setText("");
                        password.setText("");
                        username.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "username belum terdaftar", "CV Adhi Rahayu", JOptionPane.INFORMATION_MESSAGE);
                    username.setText("");
                    password.setText("");
                    username.requestFocus();
                }
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
            }
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
                        this.dispose();
                        this.setVisible(false);
                        Registrasi rs = new Registrasi();
                        rs.setVisible(true);

    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
